//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RU.Uci.OAMarket.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RU.Uci.OAMarket.Website.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent or diffuse.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string AdditionalComments {
            get {
                return ResourceManager.GetString("AdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All disciplines&gt;.
        /// </summary>
        public static string AllDisciplines {
            get {
                return ResourceManager.GetString("AllDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All institutions&gt;.
        /// </summary>
        public static string AllInstitutions {
            get {
                return ResourceManager.GetString("AllInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All languages&gt;.
        /// </summary>
        public static string AllLanguages {
            get {
                return ResourceManager.GetString("AllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Processing Charges (APC).
        /// </summary>
        public static string ArticleProcessingCharges {
            get {
                return ResourceManager.GetString("ArticleProcessingCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Base Score.
        /// </summary>
        public static string AverageBaseScore {
            get {
                return ResourceManager.GetString("AverageBaseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average subscores.
        /// </summary>
        public static string AverageSubscores {
            get {
                return ResourceManager.GetString("AverageSubscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Valuation Score.
        /// </summary>
        public static string AverageValuationScore {
            get {
                return ResourceManager.GetString("AverageValuationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string Badges {
            get {
                return ResourceManager.GetString("Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Score.
        /// </summary>
        public static string BaseScore {
            get {
                return ResourceManager.GetString("BaseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Score for this journal.
        /// </summary>
        public static string BaseScoreForThisJournal {
            get {
                return ResourceManager.GetString("BaseScoreForThisJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date awarded.
        /// </summary>
        public static string DateAwarded {
            get {
                return ResourceManager.GetString("DateAwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date received.
        /// </summary>
        public static string DateReceived {
            get {
                return ResourceManager.GetString("DateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string DateUpdated {
            get {
                return ResourceManager.GetString("DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines.
        /// </summary>
        public static string Disciplines {
            get {
                return ResourceManager.GetString("Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount price.
        /// </summary>
        public static string DiscountPrice {
            get {
                return ResourceManager.GetString("DiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit price.
        /// </summary>
        public static string EditPrice {
            get {
                return ResourceManager.GetString("EditPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished your rating.
        /// </summary>
        public static string FinishedYourRating {
            get {
                return ResourceManager.GetString("FinishedYourRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to website.
        /// </summary>
        public static string GoToWebsite {
            get {
                return ResourceManager.GetString("GoToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutional price.
        /// </summary>
        public static string InstitutionalPrice {
            get {
                return ResourceManager.GetString("InstitutionalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSN.
        /// </summary>
        public static string ISSN {
            get {
                return ResourceManager.GetString("ISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSNs.
        /// </summary>
        public static string ISSNs {
            get {
                return ResourceManager.GetString("ISSNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        public static string Journals {
            get {
                return ResourceManager.GetString("Journals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Score Card.
        /// </summary>
        public static string JournalScoreCard {
            get {
                return ResourceManager.GetString("JournalScoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Score Cards.
        /// </summary>
        public static string JournalScoreCards {
            get {
                return ResourceManager.GetString("JournalScoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last paid price.
        /// </summary>
        public static string LastPaidPrice {
            get {
                return ResourceManager.GetString("LastPaidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last standard price.
        /// </summary>
        public static string LastStandardPrice {
            get {
                return ResourceManager.GetString("LastStandardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum price.
        /// </summary>
        public static string MaximumPrice {
            get {
                return ResourceManager.GetString("MaximumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean score.
        /// </summary>
        public static string MeanScore {
            get {
                return ResourceManager.GetString("MeanScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Base Score.
        /// </summary>
        public static string MinimumBaseScore {
            get {
                return ResourceManager.GetString("MinimumBaseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Valuation Score.
        /// </summary>
        public static string MinimumValuationScore {
            get {
                return ResourceManager.GetString("MinimumValuationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fee.
        /// </summary>
        public static string NoFee {
            get {
                return ResourceManager.GetString("NoFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reviewers.
        /// </summary>
        public static string NumberOfReviewers {
            get {
                return ResourceManager.GetString("NumberOfReviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OA Journal.
        /// </summary>
        public static string OAJournal {
            get {
                return ResourceManager.GetString("OAJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OA Journals.
        /// </summary>
        public static string OAJournals {
            get {
                return ResourceManager.GetString("OAJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Organisation {
            get {
                return ResourceManager.GetString("Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid prices.
        /// </summary>
        public static string PaidPrices {
            get {
                return ResourceManager.GetString("PaidPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price information.
        /// </summary>
        public static string PriceInformation {
            get {
                return ResourceManager.GetString("PriceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  per article.
        /// </summary>
        public static string PricePerArticle {
            get {
                return ResourceManager.GetString("PricePerArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  per page.
        /// </summary>
        public static string PricePerPage {
            get {
                return ResourceManager.GetString("PricePerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish a Journal Score Card for this journal.
        /// </summary>
        public static string PublishScoreCardForThisJournal {
            get {
                return ResourceManager.GetString("PublishScoreCardForThisJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish your Score Card.
        /// </summary>
        public static string PublishYourScoreCard {
            get {
                return ResourceManager.GetString("PublishYourScoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Open Access Market.
        /// </summary>
        public static string QualityOpenAccessMarket {
            get {
                return ResourceManager.GetString("QualityOpenAccessMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radboud University Nijmegen.
        /// </summary>
        public static string RadboudUniversityNijmegen {
            get {
                return ResourceManager.GetString("RadboudUniversityNijmegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regardless of currency.
        /// </summary>
        public static string RegardlessOfCurrency {
            get {
                return ResourceManager.GetString("RegardlessOfCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data.
        /// </summary>
        public static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Card.
        /// </summary>
        public static string ScoreCard {
            get {
                return ResourceManager.GetString("ScoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Card aspects.
        /// </summary>
        public static string ScoreCardAspects {
            get {
                return ResourceManager.GetString("ScoreCardAspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Card published.
        /// </summary>
        public static string ScoreCardPublished {
            get {
                return ResourceManager.GetString("ScoreCardPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score journal.
        /// </summary>
        public static string ScoreJournal {
            get {
                return ResourceManager.GetString("ScoreJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score this journal.
        /// </summary>
        public static string ScoreThisJournal {
            get {
                return ResourceManager.GetString("ScoreThisJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ISSN.
        /// </summary>
        public static string SearchByISSN {
            get {
                return ResourceManager.GetString("SearchByISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by publisher.
        /// </summary>
        public static string SearchByPublisher {
            get {
                return ResourceManager.GetString("SearchByPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by journal title.
        /// </summary>
        public static string SearchByTitle {
            get {
                return ResourceManager.GetString("SearchByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search journal.
        /// </summary>
        public static string SearchJournal {
            get {
                return ResourceManager.GetString("SearchJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard APC.
        /// </summary>
        public static string StandardAPC {
            get {
                return ResourceManager.GetString("StandardAPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard price.
        /// </summary>
        public static string StandardPrice {
            get {
                return ResourceManager.GetString("StandardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard prices.
        /// </summary>
        public static string StandardPrices {
            get {
                return ResourceManager.GetString("StandardPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Journal Score Cards of authors en editors.
        /// </summary>
        public static string SubmittedOnly {
            get {
                return ResourceManager.GetString("SubmittedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your friends.
        /// </summary>
        public static string TellYourFriends {
            get {
                return ResourceManager.GetString("TellYourFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Netherlands.
        /// </summary>
        public static string TheNetherlands {
            get {
                return ResourceManager.GetString("TheNetherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be visible for one year.
        /// </summary>
        public static string ThisWillBeVisible {
            get {
                return ResourceManager.GetString("ThisWillBeVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all journals with the same publisher.
        /// </summary>
        public static string UpdateAllJournalsOfPublisher {
            get {
                return ResourceManager.GetString("UpdateAllJournalsOfPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation Score.
        /// </summary>
        public static string ValuationScore {
            get {
                return ResourceManager.GetString("ValuationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View online.
        /// </summary>
        public static string ViewOnline {
            get {
                return ResourceManager.GetString("ViewOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your prices.
        /// </summary>
        public static string YourPrices {
            get {
                return ResourceManager.GetString("YourPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score.
        /// </summary>
        public static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
    }
}
