//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RU.Uci.OAMarket.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RU.Uci.OAMarket.Website.Resources.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failure.
        /// </summary>
        public static string Account_ExternalLoginFailure_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your institutional account.
        /// </summary>
        public static string Account_Login_Help {
            get {
                return ResourceManager.GetString("Account_Login_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to publish score cards, you need to log in. You can log in by using your own institutional credentials. You cannot create an account, you have to have an institutional account to log in..
        /// </summary>
        public static string Account_Login_Instructions_Part1 {
            get {
                return ResourceManager.GetString("Account_Login_Instructions_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log in, just click on the image on the right, select your institution and login using your own institutional credentials. After succesfully logging in, you will automatically be returned to this website..
        /// </summary>
        public static string Account_Login_Instructions_Part2 {
            get {
                return ResourceManager.GetString("Account_Login_Instructions_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the text are below you can enter ISSNs of journals to be imported..
        /// </summary>
        public static string Admin_Import_Text {
            get {
                return ResourceManager.GetString("Admin_Import_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import journals.
        /// </summary>
        public static string Admin_Import_Title {
            get {
                return ResourceManager.GetString("Admin_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal with the following ISSNs were not imported as they could not be found.
        /// </summary>
        public static string Admin_Imported_Failure {
            get {
                return ResourceManager.GetString("Admin_Imported_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal with the following ISSNs were successfully imported.
        /// </summary>
        public static string Admin_Imported_Success {
            get {
                return ResourceManager.GetString("Admin_Imported_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals import result.
        /// </summary>
        public static string Admin_Imported_Title {
            get {
                return ResourceManager.GetString("Admin_Imported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import journals.
        /// </summary>
        public static string Admin_Index_ImportJournals {
            get {
                return ResourceManager.GetString("Admin_Index_ImportJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can choose from several administrative tasks.
        /// </summary>
        public static string Admin_Index_Text {
            get {
                return ResourceManager.GetString("Admin_Index_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update journals.
        /// </summary>
        public static string Admin_Index_UpdateJournals {
            get {
                return ResourceManager.GetString("Admin_Index_UpdateJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the text are below you can enter ISSNs of journals to be updated. Please note that the existing information will be overwritten, which means that the publisher, language, country and disciplines will all be overwritten..
        /// </summary>
        public static string Admin_Update_Text {
            get {
                return ResourceManager.GetString("Admin_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update journals.
        /// </summary>
        public static string Admin_Update_Title {
            get {
                return ResourceManager.GetString("Admin_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal with the following ISSNs were not updated as they could not be found.
        /// </summary>
        public static string Admin_Updated_Failure {
            get {
                return ResourceManager.GetString("Admin_Updated_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal with the following ISSNs were successfully updated.
        /// </summary>
        public static string Admin_Updated_Success {
            get {
                return ResourceManager.GetString("Admin_Updated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals update result.
        /// </summary>
        public static string Admin_Updated_Title {
            get {
                return ResourceManager.GetString("Admin_Updated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quality Open Access Market helps you publish in serious, transparant OA journals, and avoid the predatory ones..
        /// </summary>
        public static string Carousel_HelpsPublish_Text {
            get {
                return ResourceManager.GetString("Carousel_HelpsPublish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help publish.
        /// </summary>
        public static string Carousel_HelpsPublish_Title {
            get {
                return ResourceManager.GetString("Carousel_HelpsPublish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to see if your institute has bargained a better price..
        /// </summary>
        public static string Carousel_LoginToCompare_Text {
            get {
                return ResourceManager.GetString("Carousel_LoginToCompare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare discount.
        /// </summary>
        public static string Carousel_LoginToCompare_Title {
            get {
                return ResourceManager.GetString("Carousel_LoginToCompare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute to the website by scoring a journal.
        /// </summary>
        public static string Carousel_ScoreJournal_Text {
            get {
                return ResourceManager.GetString("Carousel_ScoreJournal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score a journal.
        /// </summary>
        public static string Carousel_ScoreJournal_Title {
            get {
                return ResourceManager.GetString("Carousel_ScoreJournal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                For long, SURF has been convinced that in the OA paradigm, next to price quality is a critical issue. For established journals the Journal Impact Factor, though controversial, is used as a proxy for quality but for young journals there is no such quality indicator whatsoever. This is a specific handicap for young OA journals whereas young subscription journals are often just included in Big Deal packages. The outcomes of the &lt;a href=&quot;http://project-soap.eu/report-from-the-soap-symposium [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_BriefHistory_Text {
            get {
                return ResourceManager.GetString("Home_About_BriefHistory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief history.
        /// </summary>
        public static string Home_About_BriefHistory_Title {
            get {
                return ResourceManager.GetString("Home_About_BriefHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Overall, the builders have tried to apply Einstein’s razor: “Make web sites as simple as possible, but not simpler.”&lt;/p&gt;.
        /// </summary>
        public static string Home_About_EinsteinRazor_Text {
            get {
                return ResourceManager.GetString("Home_About_EinsteinRazor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstein’s razor.
        /// </summary>
        public static string Home_About_EinsteinRazor_Title {
            get {
                return ResourceManager.GetString("Home_About_EinsteinRazor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;QOAM allows filtering per discipline. Thus the varied recognition of the different aspects over the disciplines can be taken into account. E.g. if speed of publication is less important in a specific discipline all journals in this discipline will produce a low subscore for the aspect ‘process’, which might be their Base Score. As in QOAM journals are ranked by default according to their Base score, a general search would result in a place at the bottom of the list for this journals. Within their own dis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_FilteringPerDiscipline_Text {
            get {
                return ResourceManager.GetString("Home_About_FilteringPerDiscipline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering per discipline.
        /// </summary>
        public static string Home_About_FilteringPerDiscipline_Title {
            get {
                return ResourceManager.GetString("Home_About_FilteringPerDiscipline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                First and for all, QOAM aims at &lt;strong&gt;authors&lt;/strong&gt; who want to publish their article in open access in a high quality journal and for a reasonable price. Then there is the &lt;strong&gt;library community&lt;/strong&gt;. In the subscription period libraries were invaluable to  academia when building up high quality collections. The Big Deals with their take-it-or-leave-it approach seemed to make this capacity redundant. QOAM enables libraries to apply this competence anew in the open access wo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_ForWhom_Text {
            get {
                return ResourceManager.GetString("Home_About_ForWhom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For whom is QOAM useful?.
        /// </summary>
        public static string Home_About_ForWhom_Title {
            get {
                return ResourceManager.GetString("Home_About_ForWhom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Open Access Market is primarily for authors who want to publish their article in open access in a high quality journal and for a reasonable price..
        /// </summary>
        public static string Home_About_Introduction {
            get {
                return ResourceManager.GetString("Home_About_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	In QOAM quality of a journal is determined by the academic community itself via so called Journal Score Cards. A Journal Score Card is a questionnaire resulting in subscores for five critical aspects of a journal. Four of them – Editorial information, Peer review, Governance and Process - are based on the journal’s website. The fifth – Valuation – is a reality check, preferably based on experience with the submission of an article to the journal. The lowest subscore of the four web site related aspect [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_JournalScoreCards_Text {
            get {
                return ResourceManager.GetString("Home_About_JournalScoreCards_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Score Cards.
        /// </summary>
        public static string Home_About_JournalScoreCards_Title {
            get {
                return ResourceManager.GetString("Home_About_JournalScoreCards_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For standard price information QOAM links directly to the website of a journal. However, a growing number of institutions, and more specifically their libraries, succeed in negotiating better prices for their community via memberships, licences or other agreements. Unfortunately, publishers often include non-disclosure clauses in their contracts. Therefore, prices may not always be referred to directly on the QOAM website, but per journal QOAM will list the licensed institutes. Searching authors can see  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_PriceInformation_Text {
            get {
                return ResourceManager.GetString("Home_About_PriceInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price information.
        /// </summary>
        public static string Home_About_PriceInformation_Title {
            get {
                return ResourceManager.GetString("Home_About_PriceInformation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;When scientific and scholarly publishing is no longer seen as copyright exploitation but as a service, as is the case in the OA paradigm, there is a need for a market where quality of the service can be matched against price. So, once the Journal Score Card was developed (see &lt;a href=&quot;#brief-history&quot; title=&quot;A Brief History&quot;&gt;A brief history&lt;/a&gt; below) it was a natural step to create a place where information about actual journal prices, that is publication fees, was available as well. The idea of the Qual [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_QualityOfService_Text {
            get {
                return ResourceManager.GetString("Home_About_QualityOfService_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QOAM – quality of service matched against price.
        /// </summary>
        public static string Home_About_QualityOfService_Title {
            get {
                return ResourceManager.GetString("Home_About_QualityOfService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About QOAM.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                Recently, Science Europe’s &lt;a href=&quot;http://www.scienceeurope.org/uploads/Public%20documents%20and%20speeches/SE_OA_Pos_Statement.pdf&quot; title=&quot;Position Statement&quot;&gt;Position Statement&lt;/a&gt; has reconfirmed the Open Access imperative. 
        ///            &lt;/p&gt;
        ///
        ///            &lt;blockquote&gt;“Research publications are one of the main results of the research process and the Research Performing and Research Funding Organisations that comprise Science Europe share the vision of increasing the impact and redu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_Why_Text {
            get {
                return ResourceManager.GetString("Home_About_Why_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why?.
        /// </summary>
        public static string Home_About_Why_Title {
            get {
                return ResourceManager.GetString("Home_About_Why_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        public static string Home_Contact_ContactPerson {
            get {
                return ResourceManager.GetString("Home_Contact_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to process the contact form. Please try again..
        /// </summary>
        public static string Home_Contact_Form_Error {
            get {
                return ResourceManager.GetString("Home_Contact_Form_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the contact information and then submit the form..
        /// </summary>
        public static string Home_Contact_Form_Legend {
            get {
                return ResourceManager.GetString("Home_Contact_Form_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Radboudhof (4th floor).
        /// </summary>
        public static string Home_Contact_OfficeLocation {
            get {
                return ResourceManager.GetString("Home_Contact_OfficeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal delivery.
        /// </summary>
        public static string Home_Contact_PostalDelivery {
            get {
                return ResourceManager.GetString("Home_Contact_PostalDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact Leo through the form below:.
        /// </summary>
        public static string Home_Contact_Text {
            get {
                return ResourceManager.GetString("Home_Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Home_Contact_Title {
            get {
                return ResourceManager.GetString("Home_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting address.
        /// </summary>
        public static string Home_Contact_VisitingAddress {
            get {
                return ResourceManager.GetString("Home_Contact_VisitingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was successfully sent to us!.
        /// </summary>
        public static string Home_ContactSent_Text {
            get {
                return ResourceManager.GetString("Home_ContactSent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Home_ContactSent_Title {
            get {
                return ResourceManager.GetString("Home_ContactSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;A. in QOAM’s &lt;a href=&quot;{0}&quot; title=&quot;searching section&quot;&gt;searching section?&lt;/a&gt;&lt;/h4&gt;
        ///
        ///            &lt;p&gt;
        ///                The reason is that for this journal a Journal Score Card has not been published yet. To remedy this, go to the “I want to publish a Journal Score Card” section on QOAM’s main page and publish a JSC for the journal in question. Alternatively, ask your library to do so.
        ///            &lt;/p&gt;
        ///
        ///            &lt;h4&gt;B. in QOAM’s &lt;a href=&quot;{1}&quot; title=&quot;scoring section&quot;&gt;scoring section?&lt;/a&gt;&lt;/h4&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_CantFindJournal_Text {
            get {
                return ResourceManager.GetString("Home_Faq_CantFindJournal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don’t I find a specific journal in QOAM?.
        /// </summary>
        public static string Home_Faq_CantFindJournal_Title {
            get {
                return ResourceManager.GetString("Home_Faq_CantFindJournal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don’t I find a specific journal.
        /// </summary>
        public static string Home_Faq_CantFindJournal_Title_Short {
            get {
                return ResourceManager.GetString("Home_Faq_CantFindJournal_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;QOAM is a fully open web site but only academic staff may publish Journal Score Cards in QOAM. To avoid unauthorized publishing of such cards QOAM has been registered with eduGAIN. EduGAIN interconnects identity federations around the world, simplifying access to content, services and resources for the global research and education community. This will enable staff of your institute to simply log in to the scoring section of QOAM via their institutional account. &lt;br/&gt;
        ///To effectuate this your institute h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_Connect_Institute_Text {
            get {
                return ResourceManager.GetString("Home_Faq_Connect_Institute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get my institute connected to QOAM’s scoring section?.
        /// </summary>
        public static string Home_Faq_Connect_Institute_Title {
            get {
                return ResourceManager.GetString("Home_Faq_Connect_Institute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                To avoid unqualified contributions to QOAM, only members of the academic community may publish Journal Score Cards. Membership will be controlled by federated authentication via trusted third parties like SURFconext in the Netherlands. Per person only one JSC may be published for a specific journal. Published Journal Score Cards are non-anonymous. Their authors can be contacted by other members of the academic community via the &lt;a href=&quot;{0}&quot; title=&quot;Profiles section&quot;&gt;Profiles section&lt;/a&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_Framing_Text {
            get {
                return ResourceManager.GetString("Home_Faq_Framing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is QOAM prone to improper use?.
        /// </summary>
        public static string Home_Faq_Framing_Title {
            get {
                return ResourceManager.GetString("Home_Faq_Framing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Author centric, QOAM provides all journals that offer open access publishing. This entails hybrid journals. Some hybrid journals manage to generate a double income by charging both readers (via full library subscriptions) and authors (via full publication fees).&lt;br/&gt;
        ///The initiators of QOAM despise this ‘double dipping’ but QOAM is not the instrument to combat this directly. However, if institutions succeed in negotiating journal licenses that end these practices, the license results and more specificall [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_HybridJournalsIncluded_Text {
            get {
                return ResourceManager.GetString("Home_Faq_HybridJournalsIncluded_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are hybrid journals also included in QOAM?.
        /// </summary>
        public static string Home_Faq_HybridJournalsIncluded_Title {
            get {
                return ResourceManager.GetString("Home_Faq_HybridJournalsIncluded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Metrics for QOAM must apply to young journals because most  journals which are born OA are in their infancy. Therefore, the Journal Impact Factor is not included. The Leiden institute CWTS developed an Editorial Board Indicator, a metric for the scientific impact of the editorial board. The main obstacle for applying it is the problem of identifying the board members; just a name and an affiliation are not enough for that. The importance of having a clear identification of the Editorial Board members of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_NoMetrics_Text {
            get {
                return ResourceManager.GetString("Home_Faq_NoMetrics_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why does QOAM not include metrics as a quality proxy?.
        /// </summary>
        public static string Home_Faq_NoMetrics_Title {
            get {
                return ResourceManager.GetString("Home_Faq_NoMetrics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                QOAM is in the overlap of three domains: (1) Quality, (2) Open Access, (3) Market. Do subscription journals fit into these domains?&lt;br /&gt;
        ///                Ad 1. Quality. Yes. The Journal Score Card is business model neutral.&lt;br /&gt;
        ///                Ad 2. Open Access. No. Subscription is at odds with Open Access.
        ///                &lt;br /&gt;
        ///                Ad 3. Market. No. The current Big Deal packages obscure any market idea.
        ///                &lt;br /&gt;
        ///                So, subscription journa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Faq_SubscriptionJournalsNotIncluded_Text {
            get {
                return ResourceManager.GetString("Home_Faq_SubscriptionJournalsNotIncluded_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are subscription journals not included in QOAM?.
        /// </summary>
        public static string Home_Faq_SubscriptionJournalsNotIncluded_Title {
            get {
                return ResourceManager.GetString("Home_Faq_SubscriptionJournalsNotIncluded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Home_Faq_Title {
            get {
                return ResourceManager.GetString("Home_Faq_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to publish a&lt;br/&gt; Journal Score Card.
        /// </summary>
        public static string Home_Index_Score {
            get {
                return ResourceManager.GetString("Home_Index_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for an&lt;br /&gt;Open Access Journal.
        /// </summary>
        public static string Home_Index_Search {
            get {
                return ResourceManager.GetString("Home_Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Open Access Market.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                In QOAM journals are ranked by default in order of their Base Score. So, a journal at the top of the list, i.e. with a high Base Score, has a web site that addresses all the journal aspects adequately. On the other hand, a journal with a low Base Score has at least one weak aspect, but may still be strong in other respects. In order to climb on the list a journal must address its weakest aspect.
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///                Next to the Base score the Valuation sco [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_JournalScoreCard_HowAreJournalScoreCardsUsed_Text {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_HowAreJournalScoreCardsUsed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are JSCs used in QOAM?.
        /// </summary>
        public static string Home_JournalScoreCard_HowAreJournalScoreCardsUsed_Title {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_HowAreJournalScoreCardsUsed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show it!.
        /// </summary>
        public static string Home_JournalScoreCard_ShowIt_Title {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_ShowIt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Score Card.
        /// </summary>
        public static string Home_JournalScoreCard_Title {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                A Journal Score Card (JSC) is a questionnaire on five relevant journal aspects. Four of them – Editorial information, Peer review, Governance and Process - are based on the journal’s website. The fifth – Valuation – is a reality check, preferably based on experience with the submission of an article to the journal.  Every aspect has some bullets and each bullet can be rated from 1 to 5. The average of these ratings is called the subscore for this aspect. The lowest subscore of the four  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_JournalScoreCard_WhatIsJournalScoreCard_Text {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_WhatIsJournalScoreCard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a Journal Score Card?.
        /// </summary>
        public static string Home_JournalScoreCard_WhatIsJournalScoreCard_Title {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_WhatIsJournalScoreCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	Members of the academic community with a Higher Education (HE) institutional account can select open access and hybrid journals from QOAM’s &lt;a href=&quot;{0}&quot; title=&quot;Scoring section&quot;&gt;scoring section&lt;/a&gt;. (See the FAQ &lt;a href=&quot;{1}&quot; title=&quot;Why are so called hybrid journals also included in QOAM?&quot;&gt;“Why are so called hybrid journals also included in QOAM?”&lt;/a&gt;) Then QOAM offers the opportunity to publish a Journal Score Card for one or more of the selected journals. Per person only one JSC may be published for [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_JournalScoreCard_WhoMayPublish_Text {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_WhoMayPublish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who may publish JSCs in QOAM?.
        /// </summary>
        public static string Home_JournalScoreCard_WhoMayPublish_Title {
            get {
                return ResourceManager.GetString("Home_JournalScoreCard_WhoMayPublish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement in QOAM.
        /// </summary>
        public static string Home_Organisation_Involvement {
            get {
                return ResourceManager.GetString("Home_Organisation_Involvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	Over time several people have contributed in various roles. 
        ///&lt;/p&gt;
        ///
        ///&lt;ul&gt;
        ///	&lt;li&gt;&lt;strong&gt;Discussion partners:&lt;/strong&gt; Bas Savenije, Saskia de Vries, Sijbolt Noorda, Marc Dupuis, Margreet Bouma, Natalia Grygierczyk, Wim Liebrand, Astrid van Wesenbeeck, Henk Wals, Wijnandt Mijnhardt, Maurits van der Graaf.&lt;/li&gt;
        ///	&lt;li&gt;&lt;strong&gt;Funding contributions:&lt;/strong&gt; SURF, NWO, CWTS, KNAW, Radboud University.&lt;/li&gt;
        ///	&lt;li&gt;&lt;strong&gt;Prototyping the Editorial Board Indicator:&lt;/strong&gt; Paul Wouters, Rodrigo Costas.&lt;/li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Organisation_Involvement_Text {
            get {
                return ResourceManager.GetString("Home_Organisation_Involvement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In its operational stage QOAM must be run by an independent robust service provider. &lt;a href=&quot;http://www.surfmarket.nl/Over/Paginas/Dienstverlening.aspx&quot; title=&quot;SURFmarket&quot;&gt;SURFmarket&lt;/a&gt;, already the licensee for the national package deals with the subscription publishers, has shown an interest to operate it. The organisation of QOAM is under construction..
        /// </summary>
        public static string Home_Organisation_Text {
            get {
                return ResourceManager.GetString("Home_Organisation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Home_Organisation_Title {
            get {
                return ResourceManager.GetString("Home_Organisation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website has gathered the following press reviews....
        /// </summary>
        public static string Home_Press_Description {
            get {
                return ResourceManager.GetString("Home_Press_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting links.
        /// </summary>
        public static string Home_Press_InterestingLinks {
            get {
                return ResourceManager.GetString("Home_Press_InterestingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string Home_Press_Title {
            get {
                return ResourceManager.GetString("Home_Press_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments have been made on this journal.
        /// </summary>
        public static string Journals_Comments_NoComments {
            get {
                return ResourceManager.GetString("Journals_Comments_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available at your institution.
        /// </summary>
        public static string Journals_Index_AvailableAtYourInstitution {
            get {
                return ResourceManager.GetString("Journals_Index_AvailableAtYourInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your institution.
        /// </summary>
        public static string Journals_Index_ContactInstitution {
            get {
                return ResourceManager.GetString("Journals_Index_ContactInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact journal.
        /// </summary>
        public static string Journals_Index_ContactJournal {
            get {
                return ResourceManager.GetString("Journals_Index_ContactJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Journal with Base Score.
        /// </summary>
        public static string Journals_Index_InJournalWithScore {
            get {
                return ResourceManager.GetString("Journals_Index_InJournalWithScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions that offer a discount.
        /// </summary>
        public static string Journals_Index_InstitutionsThatOfferDiscount {
            get {
                return ResourceManager.GetString("Journals_Index_InstitutionsThatOfferDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to get your discount?.
        /// </summary>
        public static string Journals_Index_LearnToGetDiscount {
            get {
                return ResourceManager.GetString("Journals_Index_LearnToGetDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to see the discount at your institution.
        /// </summary>
        public static string Journals_Index_LoginToSeeDiscount {
            get {
                return ResourceManager.GetString("Journals_Index_LoginToSeeDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published JSCs.
        /// </summary>
        public static string Journals_Index_PublishedJournalScoreCards {
            get {
                return ResourceManager.GetString("Journals_Index_PublishedJournalScoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish for only.
        /// </summary>
        public static string Journals_Index_PublishFor {
            get {
                return ResourceManager.GetString("Journals_Index_PublishFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more about &lt;a href=&quot;{0}&quot; title=&quot;Price information&quot;&gt;Price information&lt;/a&gt;..
        /// </summary>
        public static string Journals_Index_ReadMorePriceInformation {
            get {
                return ResourceManager.GetString("Journals_Index_ReadMorePriceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;strong&gt;Base Score&lt;/strong&gt; and the &lt;strong&gt;Valuation Score&lt;/strong&gt; are the outcomes of one or more &lt;a href=&quot;{0}&quot; title=&quot;Journal Score Cards&quot;&gt;Journal Score Cards&lt;/a&gt; published for this journal.
        /// </summary>
        public static string Journals_Index_ScoreText {
            get {
                return ResourceManager.GetString("Journals_Index_ScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OA Journals.
        /// </summary>
        public static string Journals_Index_Title {
            get {
                return ResourceManager.GetString("Journals_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to publish in this journal.
        /// </summary>
        public static string Journals_Index_ToPublishInThisJournal {
            get {
                return ResourceManager.GetString("Journals_Index_ToPublishInThisJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the institution&apos;s journal license.
        /// </summary>
        public static string Journals_InstitutionJournalLicense_Title {
            get {
                return ResourceManager.GetString("Journals_InstitutionJournalLicense_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set the institution price of the journal.
        /// </summary>
        public static string Journals_InstitutionJournalPrice_SetQuotedPrice {
            get {
                return ResourceManager.GetString("Journals_InstitutionJournalPrice_SetQuotedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set the perceived price of the journal.
        /// </summary>
        public static string Journals_JournalPrice_SetPerceivedPrice {
            get {
                return ResourceManager.GetString("Journals_JournalPrice_SetPerceivedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the journal&apos;s price.
        /// </summary>
        public static string Journals_JournalPrice_Title {
            get {
                return ResourceManager.GetString("Journals_JournalPrice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the institution&apos;s journal license.
        /// </summary>
        public static string Journals_Prices_EditInstitutionJournalLicense {
            get {
                return ResourceManager.GetString("Journals_Prices_EditInstitutionJournalLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the journal&apos;s price.
        /// </summary>
        public static string Journals_Prices_EditJournalPrice {
            get {
                return ResourceManager.GetString("Journals_Prices_EditJournalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the institution&apos;s price see the &lt;a href=&quot;{0}&quot; title=&quot;Journal website&quot;&gt;web site&lt;/a&gt;.
        /// </summary>
        public static string Journals_Prices_ForInstitutionPriceSeeWebsite {
            get {
                return ResourceManager.GetString("Journals_Prices_ForInstitutionPriceSeeWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the standard price see the web site of this journal.
        /// </summary>
        public static string Journals_Prices_ForStandardPriceSeeWebsite {
            get {
                return ResourceManager.GetString("Journals_Prices_ForStandardPriceSeeWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your institution has a special license for this journal..
        /// </summary>
        public static string Journals_Prices_InstitutionPriceForInstitution {
            get {
                return ResourceManager.GetString("Journals_Prices_InstitutionPriceForInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, {0} institution(s) have a special license for this journal. View &lt;a id=&quot;{1}-viewInstitutionJournalPrices&quot; title=&quot;View the institutional prices&quot;&gt;the list of institution prices&lt;/a&gt;..
        /// </summary>
        public static string Journals_Prices_InstitutionPricesForJournal {
            get {
                return ResourceManager.GetString("Journals_Prices_InstitutionPricesForJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your institution does not have a special license for this journal..
        /// </summary>
        public static string Journals_Prices_NoInstitutionPriceForInstitution {
            get {
                return ResourceManager.GetString("Journals_Prices_NoInstitutionPriceForInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no institutions with a discount for this journal..
        /// </summary>
        public static string Journals_Prices_NoInstitutionPrices {
            get {
                return ResourceManager.GetString("Journals_Prices_NoInstitutionPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, there are no institutions with a special license for this journal..
        /// </summary>
        public static string Journals_Prices_NoInstitutionPricesForJournal {
            get {
                return ResourceManager.GetString("Journals_Prices_NoInstitutionPricesForJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there is no actual price evidence for this journal..
        /// </summary>
        public static string Journals_Prices_NoJournalPricesForJournal {
            get {
                return ResourceManager.GetString("Journals_Prices_NoJournalPricesForJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no paid prices for this journal..
        /// </summary>
        public static string Journals_Prices_NoPaidPrices {
            get {
                return ResourceManager.GetString("Journals_Prices_NoPaidPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently paid.
        /// </summary>
        public static string Journals_Prices_RecentlyPaid {
            get {
                return ResourceManager.GetString("Journals_Prices_RecentlyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all paid prices.
        /// </summary>
        public static string Journals_Prices_ViewPaidPrices {
            get {
                return ResourceManager.GetString("Journals_Prices_ViewPaidPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all prices found on the website.
        /// </summary>
        public static string Journals_Prices_ViewStandardPrices {
            get {
                return ResourceManager.GetString("Journals_Prices_ViewStandardPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices found on the website.
        /// </summary>
        public static string Journals_Prices_ViewStandardPricesFound {
            get {
                return ResourceManager.GetString("Journals_Prices_ViewStandardPricesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only members of the academic community may publish a JSC. See FAQ &lt;a href=&quot;{0}&quot; title=&quot;Is QOAM prone to improper use?&quot;&gt;&quot;Is QOAM prone to improper use?&quot;&lt;/a&gt;.
        /// </summary>
        public static string Journals_Scores_OnlyMembersPublish {
            get {
                return ResourceManager.GetString("Journals_Scores_OnlyMembersPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        public static string Layout_BackToTop {
            get {
                return ResourceManager.GetString("Layout_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Open Access Market.
        /// </summary>
        public static string Layout_Project_Name {
            get {
                return ResourceManager.GetString("Layout_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Open Access Market.
        /// </summary>
        public static string Layout_Title_Postfix {
            get {
                return ResourceManager.GetString("Layout_Title_Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges of {0}.
        /// </summary>
        public static string Profile_Badges_Title {
            get {
                return ResourceManager.GetString("Profile_Badges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges received.
        /// </summary>
        public static string Profile_Details_BadgesReceived {
            get {
                return ResourceManager.GetString("Profile_Details_BadgesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate another journal.
        /// </summary>
        public static string Profile_Details_RateAnotherJournal {
            get {
                return ResourceManager.GetString("Profile_Details_RateAnotherJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score card(s) expired.
        /// </summary>
        public static string Profile_Details_ScoreCardsExpired {
            get {
                return ResourceManager.GetString("Profile_Details_ScoreCardsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score card(s) published.
        /// </summary>
        public static string Profile_Details_ScoreCardsPublished {
            get {
                return ResourceManager.GetString("Profile_Details_ScoreCardsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score card(s) unfinished.
        /// </summary>
        public static string Profile_Details_ScoreCardsUnfinished {
            get {
                return ResourceManager.GetString("Profile_Details_ScoreCardsUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile of {0}.
        /// </summary>
        public static string Profile_Details_Title {
            get {
                return ResourceManager.GetString("Profile_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profile_Index_Title {
            get {
                return ResourceManager.GetString("Profile_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications of {0}.
        /// </summary>
        public static string Profile_Notifications_Title {
            get {
                return ResourceManager.GetString("Profile_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score cards of {0}.
        /// </summary>
        public static string Profile_ScoreCards_Title {
            get {
                return ResourceManager.GetString("Profile_ScoreCards_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not yet published any Journal Score Cards..
        /// </summary>
        public static string Profiles_Details_NoScoreCards {
            get {
                return ResourceManager.GetString("Profiles_Details_NoScoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may contact {0} if you are &lt;a href=&quot;{1}&quot; title=&quot;Log in to contact {0}&quot;&gt;logged in&lt;/a&gt;.
        /// </summary>
        public static string Profiles_Details_YouMayContact {
            get {
                return ResourceManager.GetString("Profiles_Details_YouMayContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the profile of.
        /// </summary>
        public static string Profiles_Edit_EditTheProfileOf {
            get {
                return ResourceManager.GetString("Profiles_Edit_EditTheProfileOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the profile.
        /// </summary>
        public static string Profiles_Edit_Title {
            get {
                return ResourceManager.GetString("Profiles_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score a journal.
        /// </summary>
        public static string Score_Index_Title {
            get {
                return ResourceManager.GetString("Score_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string Score_Journal_AdditionalComments {
            get {
                return ResourceManager.GetString("Score_Journal_AdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other additional comments you like to share.
        /// </summary>
        public static string Score_Journal_AdditionalCommentsYouWantToShare {
            get {
                return ResourceManager.GetString("Score_Journal_AdditionalCommentsYouWantToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all other cases.
        /// </summary>
        public static string Score_Journal_AllOtherCases {
            get {
                return ResourceManager.GetString("Score_Journal_AllOtherCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APC&apos;s or Article Processing Charges are calculated in various different ways. Publishers often use a default APC, or ask for chargers depending on the different variables accompanied by a calculation formula. To compare prices we use a standardised calculation..
        /// </summary>
        public static string Score_Journal_APCDescription {
            get {
                return ResourceManager.GetString("Score_Journal_APCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have published an article in this journal less than a year ago .
        /// </summary>
        public static string Score_Journal_HaveSubmittedToThisJournal {
            get {
                return ResourceManager.GetString("Score_Journal_HaveSubmittedToThisJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am an editor of this journal &lt;small&gt;(If ‘Yes’, please tick the box) &lt;/small&gt;.
        /// </summary>
        public static string Score_Journal_IsEditorOfJournal {
            get {
                return ResourceManager.GetString("Score_Journal_IsEditorOfJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your journal have third party revenues? If so, is there any risk of a potential conflict of interest? Please elucidate..
        /// </summary>
        public static string Score_Journal_IsEditorOfJournalComment {
            get {
                return ResourceManager.GetString("Score_Journal_IsEditorOfJournalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;text-left&quot;&gt;Does the journal publish articles with:&lt;/p&gt; 
        ///
        ///&lt;ul class=&quot;text-left&quot;&gt;
        ///	&lt;li&gt;A standard CC BY license? If affirmative, please tick 5.&lt;/li&gt;
        ///	&lt;li&gt;A qualified CCBY license (e.g CC BY-NC)? If affirmative, please tick 3.&lt;/li&gt;
        ///	&lt;li&gt;In all other cases, please tick 1.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Score_Journal_OpenAccessCategoryDescription {
            get {
                return ResourceManager.GetString("Score_Journal_OpenAccessCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional question: What do you think the price of publishing an article in this journal is?.
        /// </summary>
        public static string Score_Journal_OptionalQuestionPriceJournal {
            get {
                return ResourceManager.GetString("Score_Journal_OptionalQuestionPriceJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does the website of the journal tell about the publication fee?.
        /// </summary>
        public static string Score_Journal_Outdated_Publication {
            get {
                return ResourceManager.GetString("Score_Journal_Outdated_Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent or diffuse.
        /// </summary>
        public static string Score_Journal_Outdated_Publication_Absent {
            get {
                return ResourceManager.GetString("Score_Journal_Outdated_Publication_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fee.
        /// </summary>
        public static string Score_Journal_Outdated_Publication_Price_No_Fee {
            get {
                return ResourceManager.GetString("Score_Journal_Outdated_Publication_Price_No_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per article.
        /// </summary>
        public static string Score_Journal_Outdated_Publication_Price_Per_Article {
            get {
                return ResourceManager.GetString("Score_Journal_Outdated_Publication_Price_Per_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per page
        ///.
        /// </summary>
        public static string Score_Journal_Outdated_Publication_Price_Per_Page {
            get {
                return ResourceManager.GetString("Score_Journal_Outdated_Publication_Price_Per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication of my article in this journal did cost.
        /// </summary>
        public static string Score_Journal_PublicationCost {
            get {
                return ResourceManager.GetString("Score_Journal_PublicationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This effort will be rewarded. You have received a new badge:.
        /// </summary>
        public static string Score_Journal_Published_BadgeReceived {
            get {
                return ResourceManager.GetString("Score_Journal_Published_BadgeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you very much for publishing a score card.&lt;/p&gt;
        ///&lt;p&gt;Your contribution helps us to display the transparency of Open Access journals and will help editors and publishers improve their journals.&lt;p&gt;
        ///&lt;p&gt;Read more about &lt;a href=&quot;{0}&quot; title=&quot;Journal Score Cards&quot;&gt;Journal Score Cards&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string Score_Journal_Published_Summary {
            get {
                return ResourceManager.GetString("Score_Journal_Published_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qualified CC-BY licence.
        /// </summary>
        public static string Score_Journal_QualifiedCCBYLicence {
            get {
                return ResourceManager.GetString("Score_Journal_QualifiedCCBYLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard CC-BY licence.
        /// </summary>
        public static string Score_Journal_StandardCCBYLicence {
            get {
                return ResourceManager.GetString("Score_Journal_StandardCCBYLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your friends and colleagues.
        /// </summary>
        public static string Score_Journal_TellYourFriendsAndColleagues {
            get {
                return ResourceManager.GetString("Score_Journal_TellYourFriendsAndColleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score card.
        /// </summary>
        public static string Score_Journal_Title {
            get {
                return ResourceManager.GetString("Score_Journal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your discount price.
        /// </summary>
        public static string Score_Journal_YourDiscountPrice {
            get {
                return ResourceManager.GetString("Score_Journal_YourDiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge awarded at {0}.
        /// </summary>
        public static string Shared_BadgeAwardedAt {
            get {
                return ResourceManager.GetString("Shared_BadgeAwardedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;text-warning&quot;&gt;No journals could be found. This outcome is adressed in the FAQ &lt;a href=&quot;{0}&quot; title=&quot;Why don&apos;t I find a specific journal in QOAM?&quot;&gt;Why don&apos;t I find a specific journal in QOAM?&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string Shared_NoJournalsFound {
            get {
                return ResourceManager.GetString("Shared_NoJournalsFound", resourceCulture);
            }
        }
    }
}
