version: 1.0.{build}
before_build:
- ps: >-
    nuget restore

    New-Item src\Website\MachineKey.Debug.config -type file -value "<?xml version=""1.0""?><machineKey />"

    New-Item src\Website\ConnectionStrings.Debug.config -type file -value "<?xml version=""1.0""?><connectionStrings />"

    New-Item src\Website\Contact.Debug.config -type file -value "<?xml version=""1.0""?><contact />"

    New-Item src\Website\NLog.Debug.config -type file -value "<?xml version=""1.0""?><nlog />"

    New-Item src\Website\Ulrichs.Debug.config -type file -value "<?xml version=""1.0""?><ulrichs />"
build:
  verbosity: minimal