//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RU.Uci.OAMarket.Console.DataImporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RU.Uci.OAMarket.Console.DataImporter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgegeven modus: {0}.
        /// </summary>
        internal static string ExecutingMode {
            get {
                return ResourceManager.GetString("ExecutingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgegeven type: {0}.
        /// </summary>
        internal static string ExecutingType {
            get {
                return ResourceManager.GetString("ExecutingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tijdschriften geïmporteerd, waarvan {1} nieuwe tijdschriften..
        /// </summary>
        internal static string ImportedJournals {
            get {
                return ResourceManager.GetString("ImportedJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijdschriften aan het importeren....
        /// </summary>
        internal static string ImportingJournals {
            get {
                return ResourceManager.GetString("ImportingJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roep de applicatie aan met een argumenten: [TYPE] (MODUS).
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige modus opgegeven. Modus moet zijn: [insertonly|insertandupdate]..
        /// </summary>
        internal static string InvalidMode {
            get {
                return ResourceManager.GetString("InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig type opgegeven. Type moet zijn: [doajjournals|ulrichsjournals]..
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
    }
}
