//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RU.Uci.OAMarket.Console.ExpirationChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RU.Uci.OAMarket.Console.ExpirationChecker.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal bijna verlopen Score Cards: {0}.
        /// </summary>
        internal static string CheckedAlmostExpiredJournals {
            get {
                return ResourceManager.GetString("CheckedAlmostExpiredJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal gearchiveerde Score Cards: {0}.
        /// </summary>
        internal static string CheckedExpiredJournals {
            get {
                return ResourceManager.GetString("CheckedExpiredJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal spoedig verlopen Score Cards: {0}.
        /// </summary>
        internal static string CheckedSoonToBeExpiredJournals {
            get {
                return ResourceManager.GetString("CheckedSoonToBeExpiredJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties aan het sturen naar eigenaren van Score Cards die verlopen zijn....
        /// </summary>
        internal static string CheckingAlmostExpiredJournals {
            get {
                return ResourceManager.GetString("CheckingAlmostExpiredJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Cards aan het archiveren die verlopen zijn....
        /// </summary>
        internal static string CheckingExpiredJournals {
            get {
                return ResourceManager.GetString("CheckingExpiredJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn fouten opgetreden: {0}.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
    }
}
