// <auto-generated />
namespace RU.Uci.OAMarket.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class JSCEditorField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JSCEditorField));
        
        string IMigrationMetadata.Id
        {
            get { return "201401161057106_JSCEditorField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
