// <auto-generated />
namespace RU.Uci.OAMarket.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NumberOfScoreCards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberOfScoreCards));
        
        string IMigrationMetadata.Id
        {
            get { return "201403120902369_NumberOfScoreCards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
