//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QOAM.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Questions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QOAM.Website.Resources.Questions", typeof(Questions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website indicates if authors have a say in suggesting names of (non-)desired reviewers.
        /// </summary>
        public static string AuthorsAllowedToIndicateDesiredReviewers {
            get {
                return ResourceManager.GetString("AuthorsAllowedToIndicateDesiredReviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal (publisher) makes copies of published articles available in trusted third-party repositories (e.g. PubMed Central) immediately upon publication.
        /// </summary>
        public static string CopiesAreMadeInThirdPartyRepositories {
            get {
                return ResourceManager.GetString("CopiesAreMadeInThirdPartyRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal discloses the past (yearly) number of submissions, publications, and rejection rates.
        /// </summary>
        public static string DisclosesNumberOfSubmissionsPublicationsAndRejectionRates {
            get {
                return ResourceManager.GetString("DisclosesNumberOfSubmissionsPublicationsAndRejectionRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would deem this journal good value for money.
        /// </summary>
        public static string GoodValueForMoney {
            get {
                return ResourceManager.GetString("GoodValueForMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal (publisher) has clear guidelines concerning sharing and availability of data for verification purposes.
        /// </summary>
        public static string HasClearGuidelinesConcerningSharing {
            get {
                return ResourceManager.GetString("HasClearGuidelinesConcerningSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal’s website highlights issues of publication ethics (e.g. plagiarism, retraction policy), conflicts of interest, and (if applicable) codes of conduct for research in life sciences and social sciences.
        /// </summary>
        public static string HighlightsIssuesOfPublicationEthics {
            get {
                return ResourceManager.GetString("HighlightsIssuesOfPublicationEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would consider the peer-review process in this journal to be transparent.
        /// </summary>
        public static string PeerReviewProcessTransparent {
            get {
                return ResourceManager.GetString("PeerReviewProcessTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal (publisher) provides the articles with a Digital Object Identifier.
        /// </summary>
        public static string ProvidesArticlesWithDigitalObjectIdentifier {
            get {
                return ResourceManager.GetString("ProvidesArticlesWithDigitalObjectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website provides a track &amp; trace service enabling authors to follow the status of their submission (e.g. under review).
        /// </summary>
        public static string ProvidesTrackAndTraceService {
            get {
                return ResourceManager.GetString("ProvidesTrackAndTraceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published papers include information on dates of original submission and acceptance.
        /// </summary>
        public static string PublishedPapersIncludeInformationOnDatesOfSubmissionAndAcceptance {
            get {
                return ResourceManager.GetString("PublishedPapersIncludeInformationOnDatesOfSubmissionAndAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would recommend scholars to submit their work to this journal.
        /// </summary>
        public static string RecommendScholarsToSubmit {
            get {
                return ResourceManager.GetString("RecommendScholarsToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website of the journal indicates how open editorial correspondence and reviewer&apos;s comments are.
        /// </summary>
        public static string ReviewsCommentsArePublished {
            get {
                return ResourceManager.GetString("ReviewsCommentsArePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal (publisher) takes care of inclusion of its articles in relevant indexing services.
        /// </summary>
        public static string TakesCareOfInclusionInRelevantIndexingServices {
            get {
                return ResourceManager.GetString("TakesCareOfInclusionInRelevantIndexingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal website allows ratings of papers and post-publication commentaries by the community.
        /// </summary>
        public static string WebsiteAllowsRatingsAndCommentariesOfPapers {
            get {
                return ResourceManager.GetString("WebsiteAllowsRatingsAndCommentariesOfPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aims, scope, and target audience of the journal are clearly specified on the journal’s website.
        /// </summary>
        public static string WebsiteContainsAimsScopeAndReadership {
            get {
                return ResourceManager.GetString("WebsiteContainsAimsScopeAndReadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria used by reviewers to rate submissions are specified on the website.
        /// </summary>
        public static string WebsiteContainsCriteriaUsedByReviewers {
            get {
                return ResourceManager.GetString("WebsiteContainsCriteriaUsedByReviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names and affiliations of members of the editorial board are listed on the website.
        /// </summary>
        public static string WebsiteContainsNameAndAffiliationsOfMembersEditorialBoard {
            get {
                return ResourceManager.GetString("WebsiteContainsNameAndAffiliationsOfMembersEditorialBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role of members of the editorial board is explicated on the website including who will make final decisions about article acceptance (e.g., editor, associate/action editor).
        /// </summary>
        public static string WebsiteContainsRoleOfMembersEditorialBoard {
            get {
                return ResourceManager.GetString("WebsiteContainsRoleOfMembersEditorialBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website indicates whether all submissions are sent out for review.
        /// </summary>
        public static string WebsiteContainsSubmissionsReviewDetails {
            get {
                return ResourceManager.GetString("WebsiteContainsSubmissionsReviewDetails", resourceCulture);
            }
        }
    }
}
