//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QOAM.Core {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QOAM.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string BadgeLevel_Bronze {
            get {
                return ResourceManager.GetString("BadgeLevel_Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string BadgeLevel_Gold {
            get {
                return ResourceManager.GetString("BadgeLevel_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string BadgeLevel_Silver {
            get {
                return ResourceManager.GetString("BadgeLevel_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget protection.
        /// </summary>
        public static string BadgeType_BudgetProtection {
            get {
                return ResourceManager.GetString("BadgeType_BudgetProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping hand.
        /// </summary>
        public static string BadgeType_HelpingHand {
            get {
                return ResourceManager.GetString("BadgeType_HelpingHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar.
        /// </summary>
        public static string Currency_Dollar {
            get {
                return ResourceManager.GetString("Currency_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string Currency_Euro {
            get {
                return ResourceManager.GetString("Currency_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK Pound.
        /// </summary>
        public static string Currency_Pound {
            get {
                return ResourceManager.GetString("Currency_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent or diffuse.
        /// </summary>
        public static string FeeType_Absent {
            get {
                return ResourceManager.GetString("FeeType_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string FeeType_Article {
            get {
                return ResourceManager.GetString("FeeType_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fee.
        /// </summary>
        public static string FeeType_NoFee {
            get {
                return ResourceManager.GetString("FeeType_NoFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string FeeType_Page {
            get {
                return ResourceManager.GetString("FeeType_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        public static string InstitutionSortMode_Name {
            get {
                return ResourceManager.GetString("InstitutionSortMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by number of JSC&apos;s.
        /// </summary>
        public static string InstitutionSortMode_NumberOfJournalScoreCards {
            get {
                return ResourceManager.GetString("InstitutionSortMode_NumberOfJournalScoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Base Score.
        /// </summary>
        public static string JournalSortMode_BaseScore {
            get {
                return ResourceManager.GetString("JournalSortMode_BaseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by journal name.
        /// </summary>
        public static string JournalSortMode_Name {
            get {
                return ResourceManager.GetString("JournalSortMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Valuation Score.
        /// </summary>
        public static string JournalSortMode_ValuationScore {
            get {
                return ResourceManager.GetString("JournalSortMode_ValuationScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge received.
        /// </summary>
        public static string NotificationType_BadgeReceived {
            get {
                return ResourceManager.GetString("NotificationType_BadgeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted institution.
        /// </summary>
        public static string NotificationType_ContactedInstitution {
            get {
                return ResourceManager.GetString("NotificationType_ContactedInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published score card.
        /// </summary>
        public static string NotificationType_PublishedScoreCard {
            get {
                return ResourceManager.GetString("NotificationType_PublishedScoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial info.
        /// </summary>
        public static string QuestionCategory_EditorialInformation {
            get {
                return ResourceManager.GetString("QuestionCategory_EditorialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governance.
        /// </summary>
        public static string QuestionCategory_Governance {
            get {
                return ResourceManager.GetString("QuestionCategory_Governance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Access.
        /// </summary>
        public static string QuestionCategory_OpenAccess {
            get {
                return ResourceManager.GetString("QuestionCategory_OpenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review.
        /// </summary>
        public static string QuestionCategory_PeerReview {
            get {
                return ResourceManager.GetString("QuestionCategory_PeerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string QuestionCategory_Process {
            get {
                return ResourceManager.GetString("QuestionCategory_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation.
        /// </summary>
        public static string QuestionCategory_Valuation {
            get {
                return ResourceManager.GetString("QuestionCategory_Valuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Score_Absent {
            get {
                return ResourceManager.GetString("Score_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Score_Excellent {
            get {
                return ResourceManager.GetString("Score_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Score_Good {
            get {
                return ResourceManager.GetString("Score_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Score_Moderate {
            get {
                return ResourceManager.GetString("Score_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string Score_Poor {
            get {
                return ResourceManager.GetString("Score_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undecided.
        /// </summary>
        public static string Score_Undecided {
            get {
                return ResourceManager.GetString("Score_Undecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by registration date.
        /// </summary>
        public static string UserProfileSortMode_DateRegistered {
            get {
                return ResourceManager.GetString("UserProfileSortMode_DateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by institution.
        /// </summary>
        public static string UserProfileSortMode_Institution {
            get {
                return ResourceManager.GetString("UserProfileSortMode_Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        public static string UserProfileSortMode_Name {
            get {
                return ResourceManager.GetString("UserProfileSortMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by number of JSC&apos;s.
        /// </summary>
        public static string UserProfileSortMode_NumberOfJournalScoreCards {
            get {
                return ResourceManager.GetString("UserProfileSortMode_NumberOfJournalScoreCards", resourceCulture);
            }
        }
    }
}
