// <auto-generated />
namespace QOAM.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BlockedISSNs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlockedISSNs));
        
        string IMigrationMetadata.Id
        {
            get { return "201508271400052_BlockedISSNs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
