// <auto-generated />
namespace QOAM.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CornerVisitors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CornerVisitors));
        
        string IMigrationMetadata.Id
        {
            get { return "201612190828433_Corner-Visitors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
