// <auto-generated />
namespace QOAM.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BFJTrustedJournals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BFJTrustedJournals));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110826473_BFJ-Trusted-Journals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
