// <auto-generated />
namespace QOAM.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InDoajFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InDoajFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202103161946319_In-Doaj-Flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
